#!/usr/bin/env python

"""
how to use :
$ lsusb | grep Huawei | grep K3765 | <path>/<to>/reset-usb
"""

import fcntl
import os
import sys

USBDEVFS_RESET = 21780

for line in sys.stdin:
    line = line.strip()
    print(line)
    try:
        lsusb_out = line.split()
        bus = lsusb_out[1]
        device = lsusb_out[3][:-1]
        usb_path = '/dev/bus/usb/%s/%s' % (bus, device)
        print('resetting %s' % usb_path)
        with open(usb_path, 'w', os.O_WRONLY) as f:
            fcntl.ioctl(f, USBDEVFS_RESET, 0)
        print('success')
    except Exception, msg:
        print('failed: %s' % msg)
