#!/usr/bin/env python3

"""
to serve simple HTTP server + multithreaded support
"""

from http.server import SimpleHTTPRequestHandler
from socketserver import ThreadingMixIn, TCPServer
import argparse
import os

class ThreadedTCPServer(ThreadingMixIn, TCPServer):
    pass

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--bind', '-b', default='', metavar='ADDRESS',
                        help='Specify alternate bind address '
                             '[default: all interfaces]')
    parser.add_argument('--target', '-t', default='.',
                        help='Specify target path directory '
                             '[default: current working directory]')
    parser.add_argument('port', action='store',
                        default=8000, type=int,
                        nargs='?',
                        help='Specify alternate port [default: 8000]')

    args = parser.parse_args()

    if args.target != '.':
        os.chdir(args.target)

    HOST, PORT = args.bind or '0.0.0.0', args.port
    server = ThreadedTCPServer((HOST, PORT), SimpleHTTPRequestHandler)

    print("Serving HTTP on {0} port {1} (http://{0}:{1}/) ...".format(HOST, PORT))
    server.serve_forever()

# vim:ts=4:sts=4:sw=4:et:ai:
